### ISSUE TITLE
Focus for Export Launch configurations is off

### ISSUE THREAD

**Issue by jlonnberg** [eclipse-platform/eclipse.platform.debug#100]
When exporting a launch configuration from the "Debug Configuration window", the focus is left on the Debug Configurations window instead of the "Export Launch Configuration" window. This requires the user to close the "Debug Configurations" windows before being able to set focus on the "Export Launch Configuration" window.

Seen in Eclipse 2022-12

**Comment by SarikaSinha** [comment]
I am wondering why did it stop wondering since 4.25 as I don't see any change in this file.
May be something changed in the way dialog works.
