### ISSUE TITLE
show debug values inline on text editors bug

### ISSUE THREAD

**Issue by lyh061619** [eclipse-platform/eclipse.platform.debug#107]
Inline display of debug values on the text editor does not work

OS version:
win 10 pro

eclipse version
Version: 2022-12 (4.26.0)
Build id: 20221201-1913

![20230203161349](https://user-images.githubusercontent.com/15118571/216548030-a902f23d-e6f6-4845-8ee6-539fcf49d385.png)

**Comment by mickaelistria** [comment]
On this line, `nameValue` doesn't exist yet, so it cannot be resolved to a value. What happens if you jump to next line?

**Comment by lyh061619** [comment]
> On this line, `nameValue` doesn't exist yet, so it cannot be resolved to a value. What happens if you jump to next line?

The variable variablelist has a value, but it cannot be displayed during debugging. I think there is a bug in the show debug values inline on editors function. At least it cannot work normally now

**Comment by humphreygao** [comment]
https://www.eclipse.org/eclipse/news/4.23/platform.php#inline-debug-values

**Java debugger does not support it yet.**

**Comment by lyh061619** [comment]
> https://www.eclipse.org/eclipse/news/4.23/platform.php#inline-debug-values
> 
> **Java debugger does not support it yet.**

At this stage, the function support is virtually nonexistent. It is a very practical debugging aid. Why is it not valued

**Comment by merks** [comment]
There being too much to do and not enough people to do it is not the same as a feature not being valued.

**Comment by akurtakov** [comment]
As the feature is clearly supported on platform level. It should be actually requested at https://github.com/eclipse-jdt/eclipse.jdt.debug to implement support for this feature. There is nothing to be done on Platform side  thus open respective issue there.

**Comment by mickaelistria** [comment]
> At this stage, the function support is virtually nonexistent.

It is existent for debuggers built on top of LSP4E and Debug Adapter Protocol.

> It is a very practical debugging aid. Why is it not valued

Contributions to add Java support for it would probably be welcome. However, the Platform-level feature still needs improvements to scale for larger files; it currently doesn't perform well. Contributions to improve that as well would be welcome here.
