### ISSUE TITLE
The source code of some javaFx classes is no longer accessible at debugging in Eclipse

### ISSUE THREAD

**Issue by Graou74** [eclipse-platform/eclipse.platform.debug#117]
### Expected Behavior
When in debug mode the program stops on a line of code, the code of the class is visible.

### Current Behavior
Only on part of the JavaFx classes, during the debug, instead of displaying the source code of the class, the editor displays "Source not found" with a button entitled "Edit source lookup path ...".

### Context
This issue manifests in Eclipse 4.26.0 while it does not in Eclipse 4.25.0. I tried combinations with different versions of Gradle (7.6.1 and 8.0), different versions of JavaFX (16 and 19.0.2.1), different versions of JavaFX Gradle plugin (0.0.10 and 0.0.13) and different versions of JDK (15.0.4 and 19.0.2) but the result is always the same: Eclipse 4.25.0 = success and Eclipse 4.26.0 = failure.
Because of this, debugging becomes much less comfortable than before when certain JavaFX classes come into play.

### Steps to Reproduce 
In Eclipse 4.26.0 put a breakpoint on the javafx.stage.Window class (on the class declaration line) then launch in debug mode a JavaFX example which opens a window.
The source code of the class will not be accessible.

### Your Environment
MacOS 12.2
Eclipse 4.26.0
JDK 19.0.2
JavaFX 19.0.2.1
Gradle 7.6.1
JavaFX Gradle plugin 0.0.13

**Comment by Graou74** [comment]
The type filter seems correct and is exactly the same as the one in version 4.25.0 which does not have this problem.
Even by disabling certain packages (sun, jdk) the result remains the same.
![Capture d’écran 2023-03-01 à 12 28 16](https://user-images.githubusercontent.com/54896431/222128380-d92672bb-9605-4c03-bd39-3fe2fccd2fbd.jpg)

**Comment by mickaelistria** [comment]
Can you please provide a minimal project to reproduce the issue? If I'm not mistaken, javafx is not always buit-in the JDK; is it coming as an external lib in your case? What is providing this lib (Gradle)? It could be that the library isn't correctly configured in Eclipse IDE and misses the source attachment declaration.

**Comment by Graou74** [comment]
Here is the zip of the minimal Gradle project with the export of the program launch (TestJavaFXDebug class):
[ZZZ_test_JavaFx_Debug.zip](https://github.com/eclipse-platform/eclipse.platform.debug/files/10861857/ZZZ_test_JavaFx_Debug.zip)
[TestJavaFXDebug.launch.zip](https://github.com/eclipse-platform/eclipse.platform.debug/files/10861862/TestJavaFXDebug.launch.zip)
The JavaFX library is automatically managed by the Gradle plugin 'org.openjfx.javafxplugin' (see "plugins" and "javafx" blocs in the built.gradle file).
In "Run Configuration/VM arguments", there is the path of the JavaFX SDK version 19.0.2.1 installed on my system and which can be retrieved at this URL: https://gluonhq.com/products/javafx/

After the "Gradle/Refresh Gradle Project" you have to open the javafx.stage.Window class and put a breakpoint on the class declaration line :
![Capture d’écran 2023-03-01 à 15 44 31](https://user-images.githubusercontent.com/54896431/222174512-fa534176-f22a-42f1-93ee-ae360c71cb46.jpg)

Then all you have to do is run TestJavaFXDebug in debug mode.

I imported this project in Eclipse 4.25.0 and at debug everything goes correctly:
![Capture d’écran 2023-03-01 à 15 53 06](https://user-images.githubusercontent.com/54896431/222177135-e2e20cf7-a0bc-489b-bf88-3e9d0c24c921.jpg)

But in Eclipse 4.26.0 the result is different:
![Capture d’écran 2023-03-01 à 15 57 19](https://user-images.githubusercontent.com/54896431/222177343-db81b50d-a7d1-4fb9-bb2c-3283a00127f5.jpg)

**Comment by akurtakov** [comment]
Is the gradle plugin version the same? It sounds like change coming from there.

**Comment by Graou74** [comment]
Yes the Gradle plugin version is the same. I tried with an earlier version and the behavior remains exactly the same.

**Comment by merks** [comment]
I wonder whether the build path from the Properties... of the project's context menu shows whether there are source attachments like one sees here for the JRE itself:

![image](https://user-images.githubusercontent.com/208716/222180443-6933cea7-8d72-4d88-b3b1-ce09115d2f1e.png)

**Comment by Graou74** [comment]
It seems to me that the sources are well attached. Especially since they are accessible from the search by type.

![Capture d’écran 2023-03-01 à 16 20 22](https://user-images.githubusercontent.com/54896431/222183853-f282ce7a-2c70-4789-8c83-b94ace8b875e.jpg)

**Comment by merks** [comment]
They look very slightly odd though that the base paths don't start with / whereas the code jars themselves do start with /.  I wonder if it looks that way too in the environment where it works?

**Comment by Graou74** [comment]
Same in both versions:
![Capture d’écran 2023-03-01 à 16 32 17](https://user-images.githubusercontent.com/54896431/222187324-04c601f4-318e-474c-8bd0-a0996e62bf2f.jpg)

**Comment by merks** [comment]
Thanks for double checking...

**Comment by SarikaSinha** [comment]
Have you tried adding the Source path again through the Edit button and does it lead to any change in the next debugging cycle?
Can you also try disabling "Advanced Source lookup" fromJDT Debug Preferences.

**Comment by Graou74** [comment]
Many thanks SarikaSinha, disabling the 'Java/Debug/Use advanced source loockup' option solved the problem.

**Comment by mickaelistria** [comment]
@Graou74 Would you mind opening an issue to https://github.com/eclipse-jdt/eclipse.jdt.debug repeating this one and explaining that the cause is that "Use advanced source lookup" actually makes sources detection with source attachment fail?

**Comment by iloveeclipse** [comment]
There will be probably also errors reported in the Eclipse error log? if yes, please attach that log file too.

**Comment by Graou74** [comment]
@iloveeclipse Could you tell me where to find this log file?

**Comment by iloveeclipse** [comment]
`/path/to/workspace/.metadata/.log`
