### ISSUE TITLE
Selecting IAR debugger

### ISSUE THREAD

**Issue by skyluke86** [eclipse-platform/eclipse.platform.debug#123]
Installed IAR plugins for supported target 6.50.x version 6.70.3 on
Eclipse IDE for C/C++ Developers (includes Incubating components)
Version: 2023-03 (4.27.0)
Build id: 20230309-1520
OS: Windows 11, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.6+10
Java version: 17.0.6

Selecting IAR debugger, the panel has graphic issues not showing all menu and giving this error report:
An error has occurred. See error log for more details.
org/eclipse/jface/databinding/swt/SWTObservables

Attached logs

[IAR-plugins.log](https://github.com/eclipse-platform/eclipse.platform.debug/files/11027694/IAR-plugins.log)
[log.txt](https://github.com/eclipse-platform/eclipse.platform.debug/files/11027701/log.txt)

**Comment by iloveeclipse** [comment]
Please report it to IAR Systems.

**Comment by jonahgraham** [comment]
@skyluke86 when you report this to IAR you they may find it useful to know that the `org/eclipse/jface/databinding/swt/SWTObservables` was removed in Eclipse 2022-12 and was removed from the Eclipse Platform in this PR https://github.com/eclipse-platform/eclipse.platform.ui/pull/323. Eclipse CDT had to make a small change to accommodate to this API change in https://github.com/eclipse-cdt/cdt/pull/76 and that may provide some insights on what IAR needs to do. Future API changes are documented in [Deprecated API removals](https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.isv/porting/removals.html?cp=2_3_0)

**Comment by skyluke86** [comment]
thanks for the help

> @skyluke86 when you report this to IAR you they may find it useful to know that the `org/eclipse/jface/databinding/swt/SWTObservables` was removed in Eclipse 2022-12 and was removed from the Eclipse Platform in this PR [eclipse-platform/eclipse.platform.ui#323](https://github.com/eclipse-platform/eclipse.platform.ui/pull/323). Eclipse CDT had to make a small change to accommodate to this API change in [eclipse-cdt/cdt#76](https://github.com/eclipse-cdt/cdt/pull/76) and that may provide some insights on what IAR needs to do. Future API changes are documented in [Deprecated API removals](https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.isv/porting/removals.html?cp=2_3_0)

thanks for the help
