### ISSUE TITLE
Add onboarding to debug perspective

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.debug#129]
@marcushoepfner and @BeckerWdf could you also add onboarding to the debug perspective? 

It looks so empty these days....

**Comment by laeubi** [comment]
> It looks so empty these days....

Probably you should open something to debug then ;-)

One general note on that feature: 
What I noticed on my large monitor is that the font looks quite small, maybe it would be good to adapt the font size to the available space of the control?

**Comment by vogella** [comment]
> One general note on that feature: What I noticed on my large monitor is that the font looks quite small, maybe it would be good to adapt the font size to the available space of the control?

Unrelated comment to this issue.

**Comment by laeubi** [comment]
You mention it looks "empty" for me it looks empty even with the icon because the text is hardly readable, so this relates to your "empty" argument here
![grafik](https://user-images.githubusercontent.com/1331477/233009701-d964e69e-9291-4375-9d6e-2c7abd263bdd.png)

**Comment by vogella** [comment]
> You mention it looks "empty" for me it looks empty even with the icon because the text is hardly readable, so this relates to your "empty" argument here ![grafik](https://user-images.githubusercontent.com/1331477/233009701-d964e69e-9291-4375-9d6e-2c7abd263bdd.png)

You just using a crazy resolution, most likely you have the eyes of a hawk. 

Jokes aside, this issue is indended to add some content to the debug perspective. 

As for scaling the text, I think the text should be the similar size as all text, in your example your hidden project explorer. Scaling the text would IMHO look out of sync if you show other views.

**Comment by iloveeclipse** [comment]
@BeckerWdf : Matthias, do you have time for this? Would be nice to have Debug perspective also updated in 4.28.

**Comment by BeckerWdf** [comment]
> @BeckerWdf : Matthias, do you have time for this? Would be nice to have Debug perspective also updated in 4.28.

I can provide an image. Adding the text and the shortcuts (The think the F5, F6, .. shortcuts are the most prominent ones) I would leave up to somebody else.

**Comment by iloveeclipse** [comment]
IMHO would be OK to "copy/paste" stuff from resource perspective as a basic content.

**Comment by iloveeclipse** [comment]
> How do you like this?

Cool. Please add `Ctrl+3` on top, people still seem not to know that.

**Comment by merks** [comment]
Cool indeed!

**Comment by marcushoepfner** [comment]
Very nice.

We could also add a silhoutte of Uncle Bob (maybe looking angry) and text could be ("You should not be here!") :)
Explanation: Robert Martin does not like debugging, he favors good unit tests (so as I).

**Comment by vogella** [comment]
I'm a bit late to the thank you party but also thanks from my side, looks very nice.
