### ISSUE TITLE
Memory view not showing updates and edits in progress on Linux

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-platform/eclipse.platform.debug#132]
_Originally reported to CDT https://github.com/eclipse-cdt/cdt/issues/381_

The Platform Debug Memory view is not showing edits while they are happening on Linux - the edits only show up after Enter is pressed on Linux:

I start and the value is 5678, I type 4321 and press enter and the UI does not show me anything while typing.

![Peek 2023-04-25 14-42](https://user-images.githubusercontent.com/679236/234375301-ed70eddb-ca8d-4d81-9f03-9a564ef73767.gif)

Step-by-step to reproduce without using CDT:

1. Setup Eclipse Platform Debug debug development environment (you need this to get the PDA debugger that has memory view support)
2. Start runtime Eclipse
3. Create a new simple project
4. Create a pda file (e.g. [counter.pda](https://github.com/eclipse-platform/eclipse.platform.debug/blob/master/org.eclipse.debug.examples.core/samples/counter.pda))
5. Place a breakpoint in the PDA
6. Debug the pda file as a PDA launch
7. Open memory view
8. Create a memory monitor for address `0` that is `4` bytes long
9. Click on cell 0-3 and type new data - note how nothing is displayed as you type
10. Press enter - note how the cell now updates

The secondary (and possibly related bug) is that at step 8 the monitor may not appear, switching to a different view and back makes it appear.

**Comment by jonahgraham** [comment]
On Windows this behaves as expected:

![Animation](https://user-images.githubusercontent.com/679236/234380629-e736fe36-780b-416d-8098-7545a1640f44.gif)


> The secondary (and possibly related bug) is that at step 8 the monitor may not appear, switching to a different view and back makes it appear.

This seems to be a bug in PDA version as CDT does experience this part and the bug happens on Windows as well.

**Comment by kudbudeen1** [comment]
Thanks @jonahgraham. I am wondering if this bug is related to any particular GTK versions? Does GTK version upgrade offer any hope?

**Comment by jonahgraham** [comment]
The op reported the problem on this combo

OS: RHEL
OS Version - 7.8, 8.1 & 8.4
Eclipse versions - Checked with 4.16, 4.25 and 4.27(latest)
GTK - 3.22.30

**Comment by jonahgraham** [comment]
On my machine, which fails too, I have org.eclipse.swt.internal.gtk.version=3.24.20

**Comment by jonahgraham** [comment]
> Thanks @jonahgraham. I am wondering if this bug is related to any particular GTK versions? Does GTK version upgrade offer any hope?

I don't think so, but it might. GTK 3.22 is supposed to be the minimum version for Eclipse 4.28 according to https://www.eclipse.org/projects/project-plan.php?planurl=http://www.eclipse.org/eclipse/development/plans/eclipse_project_plan_4_28.xml

**Comment by jonahgraham** [comment]
I pulled up an old copy of Eclipse (4.8 aka Photon) and running it with GTK 3 produces the same issue. Running this old version with GTK2 (`SWT_GTK3=0`) makes it work properly.

Therefore this looks like it may even be an SWT bug (perhaps one uniquely exposed by Platform Debug).

Here is a gif of it working on GTK2 (`org.eclipse.swt.internal.gtk.version=2.24.32`):

![Peek 2023-04-25 20-45](https://user-images.githubusercontent.com/679236/234437955-f75d25cb-8ff5-4367-b18a-d6fdde090f7a.gif)

Note: The `SWT_GTK3` flag to disable GTK3 was [removed quite a while ago](https://www.eclipse.org/eclipse/news/4.10/platform.php#gtk2-removal) so that won't help in Eclipse >= 4.10.

**Comment by laeubi** [comment]
Maybe you can reproduce this in a standalone version of the control that is used in the memory view? At least from your screenshot it look like a non standard control.

**Comment by akurtakov** [comment]
I remember we had similar SWT bugs back in the days but haven't heard about anything similar in years. Most likely you can reproduce this in a pure SWT snippet for easier debugging.

**Comment by iloveeclipse** [comment]
For those who would like to dig into code, I assume
`org.eclipse.debug.internal.ui.viewers.TableEditorImpl.activateCellEditor()` could be of interest.

**Comment by gsrinivas37** [comment]
> I remember we had similar SWT bugs back in the days but haven't heard about anything similar in years. Most likely you can reproduce this in a pure SWT snippet for easier debugging.

@akurtakov Thanks for this information. Can you share SWT bugs that you are referring to. I can take a look into them and see what the fix was and check if similar fix would help here.

**Comment by gsrinivas37** [comment]
I reproduced that problem with steps provided by @jonahgraham and checked the code in org.eclipse.debug.internal.ui.viewers.TableEditorImpl.activateCellEditor() as suggested by @iloveeclipse but I couldn't find any hints. Everything looked good to me. (I'm not an expert at SWT or GTK draw internals). The fact that it works in windows but not in Linux suggests that the problem is in some internal platform specific drawing code.

Can someone who is more experienced in SWT internals or any contributors of this project look at this issue. I'm willing to debug the issue if someone can guide me in the right direction and provider pointers.

**Comment by jonahgraham** [comment]
In the first instance I would try to reproduce the problem in a snippet, it generally makes it easier to debug. Perhaps one of the TableEditor [swt snippets](https://www.eclipse.org/swt/snippets/) or one of the [jface snippets](https://wiki.eclipse.org/JFaceSnippets)

**Comment by gsrinivas37** [comment]
@jonahgraham OK, Thanks for pointing me to SWT snippets link, I will take TableEditor snippet and add code from AsynchronousTableViewer (which is used in Memory View) to reproduce the issue as a standalone application.

**Comment by ericwill** [comment]
> I looked at the previous bugs related to similar issue and their fixes. The fix was done in gtk_draw method of Tree widget. I tried to check if anything similar in Table gtk_draw since this one is in TableViewer but couldn't find any clue. I'm wondering if @ericwill could take a look at it as he found the fix earlier for similar issue or anyone who is an expert at SWT internals.

Sorry, I haven't been active on SWT in awhile. All I can say is that there should be a decent amount of standalone SWT snippets to reproduce this issue, as this sort of problem has been a frequent flyer in the past. :smile:

I suggest you look in the [SWT-GTK test snippet folder](https://github.com/eclipse-platform/eclipse.platform.swt/tree/master/tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets) and see if there are any there.

**Comment by kudbudeen1** [comment]
@ericwill @gsrinivas37 @iloveeclipse @jonahgraham 
This following line of code in AsyncTableRenderingViewer is causing this issue.
org.eclipse.debug.internal.ui.views.memory.renderings.AsyncTableRenderingViewer.activateCellEditor(String){
...
// The following line(:734) causes the issue
				// move cursor below editor control
				fTableCursor.moveBelow(control);
...
}

When I comment out the line "fTableCursor.moveBelow()", memory view is showing the edits as expected.

**Comment by ericwill** [comment]
Likely a drawing order issue in SWT then, if I had to guess.

**Comment by iloveeclipse** [comment]
@kudbudeen1 : please try to move the "moveBelow" code up, like here:

```
diff --git a/org.eclipse.debug.ui/ui/org/eclipse/debug/internal/ui/views/memory/renderings/AsyncTableRenderingViewer.java b/org.eclipse.debug.ui/ui/org/eclipse/debug/internal/ui/views/memory/renderings/AsyncTableRenderingViewer.java
index d9a9a92..29cc5ce 100644
--- a/org.eclipse.debug.ui/ui/org/eclipse/debug/internal/ui/views/memory/renderings/AsyncTableRenderingViewer.java
+++ b/org.eclipse.debug.ui/ui/org/eclipse/debug/internal/ui/views/memory/renderings/AsyncTableRenderingViewer.java
@@ -712,2 +712,5 @@
 
+				// move cursor below editor control
+				fTableCursor.moveBelow(control);
+
 				// Open the editor editor in selected column of the selected
@@ -731,5 +734,2 @@
 				editor.addListener(fCellEditorListener);
-
-				// move cursor below editor control
-				fTableCursor.moveBelow(control);
 			}
```

Is there some "CDT free" example that one can try with SDK only?

**Comment by gsrinivas37** [comment]
@kudbudeen1 
I see same behavior in PDA debugger (without CDT) with steps provided by @jonahgraham.
If I comment out the line "fTableCursor.moveBelow(control);", then cell edits are working fine.

@iloveeclipse I tried your suggestion to move that line above "fCursorEditor.setEditor()" and some other locations but I still see the problem. Only by removing the line, cell edits are working fine.

**Comment by gsrinivas37** [comment]
@iloveeclipse Yes. It tried your suggestion to change moveBelow/moveAbove to setVisible(false)/setVisible(true) and the cell editing works correctly.

**Comment by iloveeclipse** [comment]
@gsrinivas37 : could you please provide a PR?

**Comment by jonahgraham** [comment]
Thank you @gsrinivas37 for all the analysis and fix for this issue.

**Comment by iloveeclipse** [comment]
Can anyone who could reproduce the issue try latest nightly build with the fix please: https://download.eclipse.org/eclipse/downloads/drops4/I20230508-1800

**Comment by jonahgraham** [comment]
Verified in eclipse-SDK-I20230508-1800-linux-gtk-x86_64 with CDT 11.2.0 M2 installed on my Linux box.
