### ISSUE TITLE
Marker id ... not found when launching debuggee Eclipse

### ISSUE THREAD

**Issue by trancexpress** [eclipse-platform/eclipse.platform.debug#136]
For some time now. I've occasionally been getting an error dialog and a logged error when launching Eclipse from Eclipse (to debug some problem).

The logged error looks like this:

```
eclipse.buildId=4.28.0.I20230320-1800
java.version=17.0.6
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64 -data /data/workspaces/contributor_workspace

org.eclipse.core.resources
Error
Wed Mar 29 10:32:02 EEST 2023
Marker id 225546 not found.
```

The detailed dialog doesn't show an exception:

```
An exception stack trace is not available.
```

The launch does nothing after the dialog.

**Comment by jukzi** [comment]
you should have catched ResourceException instead of IllegalStateException. IllegalStateException is logged but not thrown.
