### ISSUE TITLE
[win] can not launch java with long classpath containing non-Ascii letter

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.debug#16]
Given a workspace in a path with a non-Ascii letter like "C:\Jörg"
And then try to launch a plain test.Main.main() the command line will be like:
`C:\Program Files\Eclipse Adoptium\jdk-17.0.3.7-hotspot\bin\java.exe -classpath C:\Jörg\projectName\test\bin test.Main`  (OK)
but when the classpath gets too long for command line then the class path argument is wrapped in a UTF-8 encoded file like
"argument.txt":
`-classpath C:\Jörg\projectName\test\bin`  (OK)
and the command line will be
`C:\Program Files\Eclipse Adoptium\jdk-17.0.3.7-hotspot\bin\java.exe "@argument.txt" test.Main`  (OK)
that will result in "java.lang.ClassNotFoundException: test.Main"  (NOK)
If i manually convert the argument.txt from UTF8 to ANSI then the command line works. 
The argument file has always to be encoded with the system encoding instead of UTF-8.
see
https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html#java-command-line-argument-files
"_The argument file must contain only ASCII characters or characters in **system default encoding** that's ASCII friendly, such as UTF-8._"

Side note: in the launch configuration dialog is a button to show command line. But the copied command line does not directly work: 1. it is missing double quotes around the executable path ("Eclipse Adoptium" contains a white space) 
2. there are line breaks instead of blanks as delimiters.

**Comment by jukzi** [comment]
the error "StandardCharsets.UTF_8" in org.eclipse.jdt.internal.launching.ClasspathShortener.createClassPathArgumentFile(String) and org.eclipse.jdt.internal.launching.ClasspathShortener.createModulePathArgumentFile(String). 

from Bug 385738 - Shorten the classpath/modulepath if necessary.

@iloveeclipse 
Please move the issue to jdt.debug

**Comment by iloveeclipse** [comment]
> Please move the issue to jdt.debug

No one can do that, thanks to clever github implementation. Please recreate there.

I assume the code that writes the file is here: https://github.com/eclipse-jdt/eclipse.jdt.debug/blob/fc676e438c304be1c336efbfa89f544d20cad6b8/org.eclipse.jdt.launching/launching/org/eclipse/jdt/internal/launching/CommandLineShortener.java#L99

Beside this, I wonder however if that is changed again with Java 18 & https://openjdk.java.net/jeps/400 ?

**Comment by laeubi** [comment]
> No one can do that, thanks to clever github implementation.

This is not true. You can click on "Transfer issue" and move it to wherever you have the appropriate access rights. You most probably need at ales "triage" access on that repository, something maybe even no committers could be gained if that helps anything.

**Comment by iloveeclipse** [comment]
> This is not true.

Unfortunately it **is** true, the repos are from different "organizations". Github doesn't allow to move issues between organizations.

**Comment by jukzi** [comment]
recreated => https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/45
