### ISSUE TITLE
"Profile As..." has not an icon in the popup-menu

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.debug#19]
While the toolbar has an icon it is missing in the popup-menu if one chooses an item from the project tree:

![grafik](https://user-images.githubusercontent.com/1331477/168568873-5691f930-7fee-4a75-97a7-6bcf38dbacc0.png)

**Comment by laeubi** [comment]
I would expect here that the same icon is shown as in the toolbar (as it is for the other menus) and the sub menu shows the individual icon (e.g. yourkit profile, php, maven, ...) because otherwise what should be shown if PHP would provide an icon and yourkit provides one?

**Comment by iloveeclipse** [comment]
> I would expect here that the same icon is shown as in the toolbar (as it is for the other menus) 

Me too.

> and the sub menu shows the individual icon (e.g. yourkit profile, php, maven, ...) because otherwise what should be shown if PHP would provide an icon and yourkit provides one?

You could try :-)

**Comment by SarikaSinha** [comment]
"Profile As" option is not shown if "Yourkit" or any profiler agent is not installed. 
Which agent is installed in the Eclipse you are working with?

**Comment by SarikaSinha** [comment]
I meant the Contextual menu showing "Profile As".
I get only "Run As" and "Debug As" option for pom.xml without yourkit. And the icon in the toolbar (after adding) is grayed out. This is how it shows up for me.
<img width="389" alt="image" src="https://user-images.githubusercontent.com/14090181/168718717-13a0daa5-c313-40a3-9c73-4ac1ee7e4b82.png">

**Comment by laeubi** [comment]
I think the menu is shown as soon as there is at least one plugin providing a `org.eclipse.debug.core.launchConfigurationTypes` with type "profile" (here possibly by the PHP extension or yourkit), if you like you can create a new textfile named test.php with the content:

```
<?php
 //just a test
?>
```

and I think when opening that it ask you to install PHP for eclipse:

> PHP Development Tools (PDT)

I tried to find yourkit in the marketplace but it seems I need to add it manually...

**Comment by laeubi** [comment]
At least in the `Customize Perspective` I can also enable this in the "Menu Visibility" Tab, then it is disabled, but the icon is missing while the other menu items (Run/Debug) has an icon:
![grafik](https://user-images.githubusercontent.com/1331477/168734601-12c4b848-07f9-4450-9792-e858b34fe900.png)
