### ISSUE TITLE
No way to start a process without "-Dfile.encoding" specified

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.debug#42]
Originally reported at https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/24

I'm trying to debug encoding issues with resources init, and using publicly available tooling (without hacking debugger code) I'm unable to start JVM **without** "-Dfile.encoding" specified, because `org.eclipse.jdt.internal.launching.StandardVMRunner.ensureEncoding(ILaunch, String[])` **always** sets **some** value

because `org.eclipse.debug.internal.core.LaunchConfiguration.launch(String, IProgressMonitor, boolean, boolean)` that always set console encoding to some value 

because `org.eclipse.debug.internal.core.LaunchManager.getEncoding(ILaunchConfiguration)` always returns some value.
That is insane...

I think I have a patch.

**Comment by SarikaSinha** [comment]
Y build has this test failing for all platforms and with Java 17 and Java 18.
https://download.eclipse.org/eclipse/downloads/drops4/Y20220703-1000/testresults/html/org.eclipse.jdt.debug.tests_ep425Y-unit-cen64-gtk3-java18_linux.gtk.x86_64_18.html

The configuration encoding should match the file system encoding expected:<UTF-[8]> but was:<UTF-[16BE]>

**Comment by iloveeclipse** [comment]
@SarikaSinha : this is fixed on master, see https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/77
