### ISSUE TITLE
Launch config view is not sorted

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-platform/eclipse.platform.debug#48]
The launch types in the launch config view are not sorted (but the launch configs contained in the root level items are sorted).
<img width="141" alt="image" src="https://user-images.githubusercontent.com/406876/176733510-ec347248-fc2c-44ab-a31e-14b9360193db.png">
Root cause is that the ViewerComparator implementation cannot deal with DelegatingStyledCellLabelProvider, therefore falling back to object.toString() when sorting those top level entries.

**Comment by SarikaSinha** [comment]
Looks good !
