### ISSUE TITLE
ANSI Support does not store the HTML format in the clipboard

### ISSUE THREAD

**Issue by mihnita** [eclipse-platform/eclipse.platform.debug#85]
Use a nightly build of Eclipse.

This is important, as HTML support as a Clipboard format for StyledText was added only 16 days ago:
https://github.com/eclipse-platform/eclipse.platform.swt/pull/395

I've used
```
Eclipse SDK
Version: 2022-12 (4.26)
Build id: I20221002-1800
```

Create a small app that outputs colors in the console.
For example a Java app doing this:
```
System.out.println("Hello \033[91mRED\033[m \033[101mRED\033[m world!");
```
Go to the console, select the text, and copy it to the clipboard using the standard Copy command
(Ctrl+C on Windows / Linux, or right-click and select Copy from the context menu)

Use an application that has the option to select what format to paste.
For example MS Word.
The HTML format shows in the list:

![image](https://user-images.githubusercontent.com/1307726/194012305-659db681-edc2-4527-8d03-89ff6af04678.png)

But pasting reveals the escape characters.

If you copy using the ANSI option "Copy Without ANSI Escapes" (Ctrl + Insert), then the escapes don't show, but the HTML option is removed:

![image](https://user-images.githubusercontent.com/1307726/194013519-b095a060-5f6c-449e-b27f-3bc4c52cb879.png)

===

The bug: the HTML format should also be available in the Clipboard without escape sequences.

**Comment by mihnita** [comment]
Please assign to me.

The code dealing with this is here:
https://github.com/eclipse-platform/eclipse.platform.debug/blob/master/org.eclipse.ui.console/src/org/eclipse/ui/internal/console/ansi/utils/AnsiClipboardUtils.java#L49

**Comment by mihnita** [comment]
The UI also has to (slightly) change, because right now it says "Put RTF in Clipboard. ..."
(see the last checkbox)

![image](https://user-images.githubusercontent.com/1307726/194015199-7841c1dc-18e2-41b6-b07d-b242fb15bb78.png)

**Comment by laeubi** [comment]
@vogella would you mind to nominate @mihnita as a committer? I think bringing ANSI support into Eclipse and the constant support for it should be sufficient?

**Comment by merks** [comment]
@laeubi Any committer can nominate someone.  Just be sure to include links to what's been contributed in the nomination. I.e., a good reason/justification.

Go to this page:

https://projects.eclipse.org/projects/eclipse.platform

Make sure you are logged in and then you can use Nominate a Committer:

![image](https://user-images.githubusercontent.com/208716/194023251-ad47e283-a49c-41ff-9ad0-8ff23663d635.png)

**Comment by laeubi** [comment]
Thanks Ed, I did this right now, please everyone vote here:
https://projects.eclipse.org/projects/eclipse.platform/elections/election-mihai-nita-committer-eclipse-platform%E2%84%A2

**Comment by iloveeclipse** [comment]
In the past I've received mails about nominations. This time I didn't. Bug?

**Comment by laeubi** [comment]
It was send to `platform-dev` list, maybe it takes some time?

**Comment by laeubi** [comment]
@mihnita your election was successful and approved by PMC, you should get committer rights on the platform repos now :+1:

**Comment by mihnita** [comment]
Thank you! :-)

For the last few days I've been reading what I was able to find about what that means
(not the right to commit, that's obvious, but the responsibilities :-)

But for now I will probably do more of the same: PR to be reviewed approved by others, more experienced.
And I will look over your shoulder to learn (your == plural, as in all the other commiters)

**Comment by akurtakov** [comment]
> Thank you! :-)
> 
> For the last few days I've been reading what I was able to find about what that means (not the right to commit, that's obvious, but the responsibilities :-)
> 
> But for now I will probably do more of the same: PR to be reviewed approved by others, more experienced. And I will look over your shoulder to learn (your == plural, as in all the other commiters)

Biggest responsibility for committers is to review others PRs. We are far beyond the time when there was someone knowledgable of certain area and being active but we can't let people contribute PRs that stay unattended. I know this happens but it's not because of anything else but "just so many hours in the day". Thus review and test PRs according to your best knowledge and request contributors to enhance them where you see fit.

**Comment by mihnita** [comment]
I've visited a couple of issues she's PRs (not mine).

And I don't seem to have any "special powers" (close issues, change tags, review or merge PRs). I didn't intend to change anything, but I've checked if the buttons / options are there.
And they are not.

So maybe someone needs to "tell GitHub" about me change in access?

Thanks,
Mihai

**Comment by akurtakov** [comment]
You should have received a mail about "paperwork", did you?

**Comment by laeubi** [comment]
It usually takes some time, but you should (after completing the paperwork) receive an email that you are invited to join the "eclipse-platform-organization". After acception the invitation you should be allowed to:

- Use the merge buttons on PRs
- rebase PRs
- assign reviewers
- reopen/close any issue

**Comment by mihnita** [comment]
Yes, I got it.
Filled in everything, and for a new email

"Thank you for completing the employer information component of the process.
You will receive further notification to complete the legal components."

And a link that I can use to check the status.
Which right now says "Awaiting legal review"

So it's all good.

If we only me, thinking that
_"your election was successful and approved by PMC, you should get committer rights on the platform repos now"_ means now-now :-)

No rush. A note on the status page says it can take up to 5 days, so nothing to worry.

Thanks,
Mihai

**Comment by akurtakov** [comment]
OK, please check again when the status page says everything is fine and if you are not able to merge get in contact with me .
