### ISSUE TITLE
StackTrace displayed is not compliant with inheritance. 

### ISSUE THREAD

**Issue by opcoach** [eclipse-platform/eclipse.platform.debug#99]
This is a very strange bug I saw today... and the first time I see it..

I have these 3 classes to override tab renderer : 

![image](https://user-images.githubusercontent.com/1716878/211370778-efaf7df4-1c57-4ac7-956b-c8d2793a1fdd.png)

The draw method is defined in all of these classes... 

In the stack trace below, I have broken in the lowest draw method, and I call the super.draw method... 

![image](https://user-images.githubusercontent.com/1716878/211371263-0a101322-a71b-4cb3-8ac6-38d5ab3784f5.png)

ANd in the stack trace the parent class is not the good one.. it should be the CTabRendering !!

![image](https://user-images.githubusercontent.com/1716878/211371689-ad381394-33fc-4f08-9533-73be93363fd1.png)

This is a really weird bug...

**Comment by opcoach** [comment]
Forgot to say,  I am using the 2022-12, project built and run with JDK-17

**Comment by mickaelistria** [comment]
It's been so forever and I don't think it's a bug. The object type is shown, and the declaring type of the current method, if different, is shown between parenthesis. It's the same thing for `CTabFolder(Widget).sendEvent` you see deeper in the stack.

**Comment by Bananeweizen** [comment]
While it has been like that forever, just exchanging those 2 types in the String concatenation might actually really be helpful. We are probably just used to reading `A(B).call()` as `B.call()`, but that's not what the label suggests on first look.

And if we could then even have different colors it would be even more awesome:
DeclaringTypeInBlack(ObjectTypeInGray).methodAndEverythingInBlack()

**Comment by opcoach** [comment]
It's been so forever ? really ? I have never seen it before even if I code quiet every day... I agree the type is defined above but this is not really handy and confusing ... 

@iloveeclipse why do you close it so quickly ?  

We are always compared to other IDE, and we must not have this kind of confusing display in the stacktrace... 

Sorry but I reopen it

**Comment by opcoach** [comment]
And especially when I am stepping in the CTabFolderRenderer (the top parent class), and I get this stack trace : 

![image](https://user-images.githubusercontent.com/1716878/211393758-5716f124-d5bf-4bd8-8df1-d69e35eb8ea1.png)

The two first are for CTabFolderRenderer
The four next are for CTabRendering
The next is for CleoCTabRendering...

And I got 6 lines with CleoCTabRendering...

**Comment by iloveeclipse** [comment]
> @iloveeclipse why do you close it so quickly ?

Here everything is said: https://github.com/eclipse-platform/eclipse.platform.debug/issues/99#issuecomment-1376013212

I don't know what can I add to that.

**Comment by jukzi** [comment]
Personally i would prefer to see Stacktraces identically to those in Exceptions from JDK. I never needed the additional type names. They are more confusing and boiler plate then helping. It's not a bug but also not a worthy feature. 
However unless there is a decision to change that style this issue should be closed.
